CREATE TABLE AGENCIA (CNPJ VARCHAR(14),  
CONSTRAINT PK_AGENCIA PRIMARY KEY (CNPJ),  
NOME VARCHAR(20),  
ENDERECO_FISICO VARCHAR(25),  
ENDERECO_TEMPORAL VARCHAR(25));

CREATE TABLE MAQUINA (CODIGO NUMBER(10),  
CONSTRAINT PK_MAQUINA PRIMARY KEY (CODIGO),  
TIPO VARCHAR(25),  
DATA_AQUISICAO DATE,  
CNPJ VARCHAR(14) NOT NULL,  
CONSTRAINT FK_MAQUINA FOREIGN KEY (CNPJ) REFERENCES AGENCIA (CNPJ));

CREATE TABLE MISSAO (CODIGO NUMBER(10),  
CONSTRAINT PK_MISSAO PRIMARY KEY (CODIGO),  
OBJETIVO VARCHAR(25));

CREATE TABLE PESSOA (CPF VARCHAR(11),  
CONSTRAINT PK_PESSOA PRIMARY KEY (CPF),  
NOME VARCHAR(20),  
DATA_NASCIMENTO DATE);

CREATE TABLE CLIENTE (CPF VARCHAR(11),  
CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF),  
CONSTRAINT FK_CLIENTE FOREIGN KEY (CPF) REFERENCES PESSOA (CPF));

CREATE TABLE FUNCIONARIO (CPF VARCHAR(11),  
CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF),  
CONSTRAINT FK_PESSOA_FUNC FOREIGN KEY (CPF) REFERENCES PESSOA (CPF),  
MENTOR VARCHAR(20),  
CONSTRAINT FK_FUNC_FUNC FOREIGN KEY (MENTOR) REFERENCES FUNCIONARIO (CPF),  
DATA_CONTRATACAO DATE);

CREATE TABLE SETOR (CNPJ VARCHAR(14),  
CONSTRAINT FK_AGENCIA_SETOR FOREIGN KEY (CNPJ) REFERENCES AGENCIA (CNPJ),  
CODIGO NUMBER(10),  
CONSTRAINT PK_SETOR PRIMARY KEY (CNPJ, CODIGO),  
CATEGORIA VARCHAR(25),  
CPF VARCHAR(11) NOT NULL UNIQUE,  
CONSTRAINT FK_FUNC_SETOR FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF));

CREATE TABLE LISTA_DESEJOS (CPF VARCHAR(11),  
DESEJO VARCHAR(30),  
CONSTRAINT PK_DESEJOS PRIMARY KEY (CPF, DESEJO),  
CONSTRAINT FK_DESEJOS FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF));

CREATE TABLE TRABALHA (CPF VARCHAR(11),  
CNPJ VARCHAR(14) NOT NULL,  
CODIGO NUMBER(10) NOT NULL,  
CONSTRAINT PK_TRABALHA PRIMARY KEY (CPF),  
CONSTRAINT FK_FUNC_TRAB FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF),  
CONSTRAINT FK_SETOR_TRAB FOREIGN KEY (CNPJ, CODIGO) REFERENCES SETOR (CNPJ, CODIGO));

CREATE TABLE VIAGEM (CLIENTE VARCHAR(11),  
CONSTRAINT FK_CLIENTE_VIAGEM FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (CPF),  
FUNCIONARIO VARCHAR(11),  
CONSTRAINT FK_FUNC_VIAGEM FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO (CPF),  
CODIGO_MAQUINA NUMBER(10),  
CONSTRAINT FK_MAQ_VIAGEM FOREIGN KEY (CODIGO_MAQUINA) REFERENCES MAQUINA (CODIGO),  
DATA_VIAGEM DATE,  
CONSTRAINT PK_VIAGEM PRIMARY KEY (CLIENTE, FUNCIONARIO, CODIGO_MAQUINA, DATA_VIAGEM));

CREATE TABLE PASSAGEM (CODIGO_RESERVA NUMBER(10),  
CONSTRAINT PK_PASSAGEM PRIMARY KEY (CODIGO_RESERVA),  
LOCAL_DESTINO VARCHAR(25),  
DATA_DESTINO DATE,  
CLIENTE VARCHAR(11) NOT NULL,  
CONSTRAINT FK_CLIENTE_PASSAGEM FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (CPF),  
FUNCIONARIO VARCHAR(11) NOT NULL,  
CONSTRAINT FK_FUNC_PASSAGEM FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO (CPF));

