CREATE TABLE AGENCIA (CNPJ VARCHAR(18),  
CONSTRAINT PK_AGENCIA PRIMARY KEY (CNPJ),  
NOME VARCHAR(30),  
ENDERECO VARCHAR(25));

CREATE TABLE MAQUINA (CODIGO NUMBER(10),  
CONSTRAINT PK_MAQUINA PRIMARY KEY (CODIGO),  
TIPO VARCHAR(25),  
DATA_AQUISICAO DATE,  
CNPJ VARCHAR(18) NOT NULL,  
CONSTRAINT FK_MAQUINA FOREIGN KEY (CNPJ) REFERENCES AGENCIA (CNPJ));

CREATE TABLE MISSAO (CODIGO NUMBER(10),  
CONSTRAINT PK_MISSAO PRIMARY KEY (CODIGO),  
OBJETIVO VARCHAR(25));

CREATE TABLE CLIENTE (CPF VARCHAR(14),  
CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF),  
NOME VARCHAR(30),  
DATA_NASCIMENTO DATE);

CREATE TABLE FUNCIONARIO (CPF VARCHAR(14),  
CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF),  
NOME VARCHAR(30),  
DATA_NASCIMENTO DATE,  
MENTOR VARCHAR(30),  
CONSTRAINT FK_FUNC_FUNC FOREIGN KEY (MENTOR) REFERENCES FUNCIONARIO (CPF),  
DATA_CONTRATACAO DATE);

CREATE TABLE SETOR (CNPJ VARCHAR(18),  
CONSTRAINT FK_AGENCIA_SETOR FOREIGN KEY (CNPJ) REFERENCES AGENCIA (CNPJ),  
CODIGO NUMBER(10),  
CONSTRAINT PK_SETOR PRIMARY KEY (CNPJ, CODIGO),  
CATEGORIA VARCHAR(25),  
CPF VARCHAR(14) NOT NULL UNIQUE,  
CONSTRAINT FK_FUNC_SETOR FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF));

CREATE TABLE LISTA_DESEJOS (CPF VARCHAR(14),  
DESEJO VARCHAR(30),  
CONSTRAINT PK_DESEJOS PRIMARY KEY (CPF, DESEJO),  
CONSTRAINT FK_DESEJOS FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF));

CREATE TABLE TRABALHA (CPF VARCHAR(14),  
CNPJ VARCHAR(18) NOT NULL,  
CODIGO NUMBER(10) NOT NULL,  
CONSTRAINT PK_TRABALHA PRIMARY KEY (CPF),  
CONSTRAINT FK_FUNC_TRAB FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF),  
CONSTRAINT FK_SETOR_TRAB FOREIGN KEY (CNPJ, CODIGO) REFERENCES SETOR (CNPJ, CODIGO));

CREATE TABLE PASSAGEM (CODIGO_RESERVA NUMBER(10),  
CONSTRAINT PK_PASSAGEM PRIMARY KEY (CODIGO_RESERVA),  
LOCAL_DESTINO VARCHAR(25),  
DATA_DESTINO DATE,  
CLIENTE VARCHAR(14) NOT NULL,  
CONSTRAINT FK_CLIENTE_PASSAGEM FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (CPF),  
FUNCIONARIO VARCHAR(14) UNIQUE NOT NULL,  
CONSTRAINT FK_FUNC_PASSAGEM FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO (CPF));

CREATE TABLE VIAGEM (CODIGO_PASSAGEM NUMBER(10),  
CONSTRAINT FK_PASSAGEM_VIAGEM FOREIGN KEY (CODIGO_PASSAGEM) REFERENCES PASSAGEM (CODIGO_RESERVA),  
FUNCIONARIO VARCHAR(14),  
CONSTRAINT FK_FUNC_VIAGEM FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO (CPF),  
CODIGO_MAQUINA NUMBER(10),  
CONSTRAINT FK_MAQ_VIAGEM FOREIGN KEY (CODIGO_MAQUINA) REFERENCES MAQUINA (CODIGO),  
DATA_VIAGEM DATE,  
CONSTRAINT PK_VIAGEM PRIMARY KEY (CODIGO_PASSAGEM, FUNCIONARIO, CODIGO_MAQUINA, DATA_VIAGEM));

CREATE TABLE MANUTENCAO (CODIGO_MAQUINA NUMBER(10),
CONSTRAINT FK_MAQ_MANU FOREIGN KEY (CODIGO_MAQUINA) REFERENCES MAQUINA (CODIGO),  
FUNCIONARIO VARCHAR(14),
CONSTRAINT FK_FUNC_MANU FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO (CPF),  
CONSTRAINT PK_MANUTENCAO PRIMARY KEY (CODIGO_MAQUINA, FUNCIONARIO));

CREATE TABLE PARTICIPA (CODIGO_MISSAO NUMBER(10),
CONSTRAINT FK_MISSAO FOREIGN KEY (CODIGO_MISSAO) REFERENCES MISSAO (CODIGO),  
FUNCIONARIO VARCHAR(14),
CONSTRAINT FK_TRABALHA FOREIGN KEY (FUNCIONARIO) REFERENCES TRABALHA (CPF),  
CONSTRAINT PK_PARTICIPA PRIMARY KEY (CODIGO_MISSAO, FUNCIONARIO));
